import type {Metadata} from 'next';
import './globals.css';
import { Providers } from './providers';
import { AppSidebar } from '@/components/app-sidebar';
import { SidebarProvider } from '@/context/sidebar-provider';
import { MainContentWrapper } from '@/components/main-content-wrapper';

export const metadata: Metadata = {
  title: 'Inmatmex Welcome',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased">
        <Providers>
          <SidebarProvider>
            <AppSidebar />
            <MainContentWrapper>
              {children}
            </MainContentWrapper>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
